[package]
name = "moodycron"
version = "0.1.0"
edition = "2024"

[dependencies]
cron = "0.15.0"
chrono = "0.4.40"
notify = "8.0.0"
log = "0.4.27"
env_logger = "0.11.8"
futures = "0.3.31"
signal-hook = "0.3.17"
sd-notify = "0.4.5"